### ISSUE TITLE
Comment on release pr when deploy is finished

### ISSUE THREAD

**Issue by steveoh** [agrc/firebase-website-deploy-composite-action#20]
Similar to how the release/tags creates a comment

<img width="467" alt="image" src="https://user-images.githubusercontent.com/325813/193730542-078869c3-2436-4a7f-9d4c-c27575653def.png">

It would be nice to comment or update the release comment when the deployment is complete containing the site url.

**Comment by stdavis** [comment]
It might also be cool to add a similar message to the release.

**Comment by steveoh** [comment]
It seems this can be closed?

**Comment by stdavis** [comment]
Agreed!
