### ISSUE TITLE
Firebase Preview expiration should be increased

### ISSUE THREAD

**Issue by stdavis** [agrc/firebase-website-deploy-composite-action#37]
I think that 3 days is too short. For example, [this PR](https://github.com/agrc/locate/pull/255) is still a hot topic five days after it was pushed. 

@steveoh, what do you think about two weeks or longer? What is the downside other than clutter?

**Comment by steveoh** [comment]
The downside is pretty much storage. The timing is rolling, meaning every commit extends that windows. I agree 3 days it too short. I wouldn't want to go much longer than 2 weeks.
